### ISSUE TITLE
ds-swig.tar.gz not available on 0.7.* or 0.8.* versions

### ISSUE THREAD

**Issue by tranzmatt** [mozilla/STT#3253]
I'm trying to build 0.7.3 of the DeepSpeech repo (which redirects to this repo) and the native_client/definitions.mk has a SWIG_DIST_URL that no longer exists:

"https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.swig.linux.amd64.b5fea54d39832d1d132d7dd921b69c0c2c9d5118/artifacts/public/ds-swig.tar.gz"

Was this removed?  The same URL is defined in 0.8.1 too

**Comment by lissyx** [comment]
It expired, please build 0.8.1

**Comment by lissyx** [comment]
err, not 0.8.1, but r0.8

**Comment by lissyx** [comment]
I'm testing if we can re-trigger older tasks to re-publish older artifacts

**Comment by lissyx** [comment]
@tranzmatt Looks like re-building and re-publishing the artifacts worked.
