### ISSUE TITLE
[Feature request] Arg params to support specifying which GPU to use

### ISSUE THREAD

**Issue by hijklmno** [mozilla/STT#3257]
Hey all,

I am currently running the open-source version 0.7.4 with the included pretrained model and scorer. I am noticing it defaults to the first GPU, as per TensorFlow defaults. My computer has 4 GPUs, and I wish to be able to specify which GPU the STT should be using so that I can run (in parallel) multiple transcription jobs. I noticed TensorFlow has the ability to [specify which GPU to use](https://www.tensorflow.org/guide/gpu#using_a_single_gpu_on_a_multi-gpu_system). Can we surface an optional arg param that takes in the GPU ID? 

I'm thinking of something like:
```
deepspeech \
--model deepspeech-0.7.4-models/deepspeech-0.7.4-models.pbmm \
--scorer deepspeech-0.7.4-models/deepspeech-0.7.4-models.scorer \
--json \
--audio /path/to/file.webm \
--gpu-id 1
```

The command will need to consider cases where corresponding GPU ID isn't found. Adding the optional param `--gpu-id` may implicitly force GPU over CPU.

I use `nvidia-smi` to discover GPUs. 

OS Platform and Distribution: Ubuntu 18.04.4 LTS
TensorFlow installed from: python [2.2.0](https://pypi.org/project/tensorflow/#description)
TensorFlow version: v1.15.2-30-g4386a66 1.15.3
Python version: 3.7.5
CUDA version: 11.0
GPU model and memory: 4x GeForce RTX 2080 

Thanks all.

**Comment by lissyx** [comment]
Just rely on cuda env variable `CUDA_VISIBLE_DEVICES` ?

**Comment by lissyx** [comment]
This is a lot of extra complexity for à usecase solved by the env variable above.
