### ISSUE TITLE
ONNX release feature request

### ISSUE THREAD

**Issue by flowpoint** [mozilla/STT#3269]
i would like you to additionally release the model in ONNX format.
it would allow many new ways of interoperability and of implementing or integrating this project.
this also softens the dependence on tensorflow.

i tried converting the model myself with [tf2onnx](https://github.com/onnx/tensorflow-onnx) but got stuck on the input/output variable names. [summarize graph](https://github.com/onnx/tensorflow-onnx#getting-started) also didnt work out for me.

releasing an ONNX version of the model would be optimal.

if not, instructions on converting would go along way too.
greetings

**Comment by flowpoint** [comment]
my hobbyist usecase is accelerated inference on jetson nano.
the steps are described in [speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt](https://developer.nvidia.com/blog/speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt/)

simply an onnx export, would allow easier implementation on different platforms with high performance.

but as stated by you above, if this isn't intended, and extra work on your end,
feel free to close this issue.

**Comment by lissyx** [comment]
> my hobbyist usecase is accelerated inference on jetson nano.
> the steps are described in [speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt](https://developer.nvidia.com/blog/speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt/)
> 
> simply an onnx export, would allow easier implementation on different platforms with high performance.
> 
> but as stated by you above, if this isn't intended, and extra work on your end,
> feel free to close this issue.

You should already be able to:
 - leverage TFLite model
 - rebuild `libmozilla_voice_stt.so` with CUDA support on that platform to leverage the GPU.

**Comment by lissyx** [comment]
So, unless there are other usecases where ONNX is really required, I'll close that. Feel free to re-open if you have other usecases where it makes more sense.

**Comment by shravanshetty1** [comment]
Just adding my use case here - I am using this model in golang using https://github.com/asticode/go-astideepspeech - however i am not sure it will support future models. If you could support ONNX we can use models easily in any other language without depending on a binding repo or python.
Also none of the frameworks (pytorch, tensorflow .etc) are easily usable in golang. Tensorflow go support makes it hard to use in production .etc.

**Comment by lissyx** [comment]
> Just adding my use case here - I am using this model in golang using https://github.com/asticode/go-astideepspeech - however i am not sure it will support future models. If you could support ONNX we can use models easily in any other language without depending on a binding repo or python.
> Also none of the frameworks (pytorch, tensorflow .etc) are easily usable in golang. Tensorflow go support makes it hard to use in production .etc.

We welcome anyone who is willing to expriment, but again, the offering of the project is model and lib. Changing to onnx brings a lot of work, much more we can take, for exactly no win.

**Comment by lissyx** [comment]
> using https://github.com/asticode/go-astideepspeech - however i am not sure it will support future models

Btw the dev of that is quite reactive, and either take cares of api changes or review our patches quickly, so there should not be any fear on that. We are close to 1.0 so the api is rather stable.
