### ISSUE TITLE
"ERROR: Config value monolithic is not defined in any .rc file" when building

### ISSUE THREAD

**Issue by pomputer** [mozilla/STT#3275]
Hi!
I am trying to build DeepSpeech using the instructions in [https://mozilla-voice-stt.readthedocs.io/en/stable/BUILDING.html](https://mozilla-voice-stt.readthedocs.io/en/stable/BUILDING.html), since the prebuilt version of TensorFlow only utilizes a minor amount of cpu power when transcribing (due to the lack of support for AVX2, I suppose).

When I run `bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so` inside the tensorflow folder I get the following error: `ERROR: Config value monolithic is not defined in any .rc file`

How can I fix this or is this a bug?
Thanks!

OS: ArchLinux
Python version: 3.8
GCC version: 10.2.0-1
Bazel version: 2.0.0

**Comment by lissyx** [comment]
Support request are to be done on Discourse, and you dont give enough context on the version you are trying to build...

**Comment by lissyx** [comment]
Though it looks like I forgot to update some part of the docs when moving to r2.3

**Comment by lissyx** [comment]
> https://mozilla-voice-stt.readthedocs.io/en/stable/BUILDING.html

This link is likely wrong, `stable` on that project is not really meaningful, this is likely a fallout from creating a new project for the new name



> since the prebuilt version of TensorFlow only utilizes a minor amount of cpu power when transcribing (due to the lack of support for AVX2, I suppose)

It is very unlikely, AVX2 to the best we could measure when the model was more complex would only account for up to 30% on the CPUs where there was the biggest difference, and around 10-15% on others.

**Comment by lissyx** [comment]
The doc is fixed now, but please use Discourse if you need further support.
